### ISSUE TITLE
OpenUPM support. Unity Package Manager

### ISSUE THREAD

**Issue by brogan89** [Real-Serious-Games/C-Sharp-Promise#108]
Hi there, it would be great if RSG Promise could be apart of [OpenUPM](https://openupm.com/) 

It will also solve dependency issue mentioned in issue #76 

However, it maybe need to be a new branch as that focuses on UPM structure while master branch still supporting plan .NET projects?

**Comment by RoryDungan** [comment]
I have set this up already - https://openupm.com/packages/com.rsg.promise/

Published from my personal account because I no longer work for RSG and I'd prefer to keep the main repo set up as a regular Visual Studio project anyway. While many people use the library in Unity there are also people who use the Nuget package in regular .NET projects, so restructuring the main branch to be a package isn't ideal. 

Migrating from my [personal repo](https://github.com/RoryDungan/C-Sharp-Promise-UPM) to a separate branch in the main repo would be a good idea but I wouldn't really like to do that without having some kid of process to automate it. Building, copying the DLL, checking out a different branch and committing it is a kind of complicated process to have to do manually all the time. Something like what [gh-pages](https://www.npmjs.com/package/gh-pages) does where it can automatically copy build artifacts to a different branch for you would be ideal.

**Comment by brogan89** [comment]
Brilliant! Don't why I didn't see that. My bad 😄

**Comment by RoryDungan** [comment]
I'll update the readme with a link to the package so that it's easier to find in future :+1:
