### ISSUE TITLE
Different results for javascript.Promise and C-Sharp-Promise

### ISSUE THREAD

**Issue by takenaoki** [Real-Serious-Games/C-Sharp-Promise#113]
Different results for javascript.Promise and C-Sharp-Promise.

Is there any problem?

## javascript
<img width="478" alt="スクリーンショット 2021-06-10 11 57 10" src="https://user-images.githubusercontent.com/26864913/121462064-f3845b80-c9ea-11eb-8d30-30c8f033fb01.png">

## C-Sharp-Promise
<img width="483" alt="スクリーンショット 2021-06-10 12 16 43" src="https://user-images.githubusercontent.com/26864913/121462089-fed78700-c9ea-11eb-8170-dc5d1d216330.png">
<img width="239" alt="スクリーンショット 2021-06-10 12 40 15" src="https://user-images.githubusercontent.com/26864913/121462095-00a14a80-c9eb-11eb-9066-47fa81861d7a.png">

**Comment by zsoi** [comment]
This is due to the way promise resolves/rejects are *always* called in the next "tick" (setTimeout) after resolve/rejection in JS, but RSG.Promise evaluates immediately without waiting a "tick" (as there usually is no such thing in C# as the event loop. But AFAIR you can implement the event loop yourself and tell RSG.Promise to utilize it).
(See A+ spec, note 3.1: https://promisesaplus.com/#point-67)

**Comment by takenaoki** [comment]
@zsoi 
Thank you for answering!
