### ISSUE TITLE
Throwing errors from the Unhandled Exception callback?

### ISSUE THREAD

**Issue by mikecann** [Real-Serious-Games/C-Sharp-Promise#16]
Hi,

I am writing unit tests and would like to "expect" an Exception. I thought that if I added a handler for UnhandledException and threw an Exception in the handler it would propagate up into the test but it doesnt seem to, it seems to get caught within the Promise.

Any ideas how I may achieve this?

Cheers,
Mike

**Comment by ashleydavis** [comment]
Can you provide an example of the unit test?

**Comment by mikecann** [comment]
```
public class CrossPromoAdProviderServiceTests
{	
	[SetUp]
	public void Setup()
	{
		Promise.UnhandledException += OnUnhandledException;
	}

	[TearDown]
	public void TearDown()
	{
		Promise.UnhandledException -= OnUnhandledException;
	}

	private void OnUnhandledException(object sender, ExceptionEventArgs e)
	{
		throw e.Exception;
	}

	[Test]
	[ExpectedException(typeof(Exception))]
	public void ExceptionOnPromiseError()
	{
		DoThingAsync();
	}

	private IPromise DoThingAsync()
	{
		return new Promise((resovle, reject) =>
		{
			throw new Exception("whoops");
		});
	}
}
```

BTW how does one test async code in Unity without async / await?

**Comment by ashleydavis** [comment]
What you are trying to do in that test won't work.

Exceptions don't work in the regular way with promises. You have to handle `Catch` if you want to test that an exception happened.

I'm not sure how you'd do this in your testing framework... in Xunit.net I'd do this:

    [Fact]
    public void MyTest()
    {
         Exception caughtException = null;

        DoThingAsync()
            .Catch(ex => caughtException = ex);

        Assert.NotNull(caughtExpection);        
    }

This particular test isn't actually asynchronous because you directly throw the exception.

You can test async code by mocking out dependencies and having them return a promise that you resolve synchronously in the test. This is the way we usually test async code at Real Serious Games.

Are you using a mocking library? We use Moq.

You can do true async testing with Xunit.net and this should work for you in the Visual Studio and Xunit tests runners, but probably won't work if you want to run your unit tests under Unity (http://bradwilson.typepad.com/blog/2012/01/xunit19.html).

**Comment by mikecann** [comment]
Hi Ashley,

Thanks for getting back.

Okay ye I thought as much, thats pretty much how I have been doing it (with the Catch) I was hoping to make it neater by using the expected exception. 

As for the Async tests ye thats how I have been doing it too with NSubstitute, I was just wondering if there was a better way that people do it in Unity, I guess not!

Thanks again :)
Mike
