### ISSUE TITLE
How can I wait for a promise result in a HttpActionResult method?

### ISSUE THREAD

**Issue by Malavos** [Real-Serious-Games/C-Sharp-Promise#21]
Hi there!

What the title says, basically.

I have an HttpActionResult in my API that calls for a method in a Third-party API.
I have the following code:

```
var aux = thirdPartyApiClient.Model.CreateModel(myModel);
            Model myResult = new Model();
            aux.Catch((exception) => {
                throw new Exception(exception.Message);
            });
            aux.Then((model) =>
            {
                myResult = model;
                //return this.Ok(model.Code);
            });

```

The problem is - I don't know in the moment how to wait for this result before returning to my application that updated result.

How can I properly wait for this result, for all the method to finish (CreateModel method) before returning something as HttpActionResult?

**Comment by ashleydavis** [comment]
Does the 3rd party API give you some sort of callback?

**Comment by theslyone** [comment]
@ashleydavis  Wonderful library but I am also caught up in this same situation. Third party API performs some data manipulation and returns an updated response or fails with reasons where required. How does one wait for the then/done/catch callbacks before dispatching an IHttpActionResult response to the calling client? 

Thanks

**Comment by RoryDungan** [comment]
Old question I know but I figured I should write a response in case anyone else comes across this. It all boils down to how the 3rd party API you're using works, so there is no single solution that will always work without seeing more info.

It depends how the 3rd party API you're 

If the API gives you a way to pass a function called when the request is completed, you can create a `new Promise<T>()` when you first send the request and then call `.Resolve(data)` on it once you have a result.

```cs
IPromise<string> HttpGet(string url)
{
    var promise = new Promise<string>();
    ThirdPartyAPI.Get(url, data => promise.Resolve(data));
    return promise;
}
``` 

Similarly, if there is an event triggered when the request completes you can connect that to a function that resolves your promise. 

If you want to convert an async/await API to use Promises you should be able to use similar code but call `ContinueWith` on the async task and resolve your new promise inside the `ContinueWith` callback. I haven't tested this method though, since async/await already has most of the functionality of Promises built-in anyway.
