### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by skyline75489** [Real-Serious-Games/C-Sharp-Promise#23]
I tried to install RSG.Promise with .NET Core 1.0, but got this error:

``` plaintext
Package RSG.Promise 1.2.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RSG.Promise 1.2.0 supports: net35 (.NETFramework,Version=v3.5)
```

**Comment by ashleydavis** [comment]
I'm not sure how we can achieve this. 

We need the promise library for .Net 3.5.  

Do you know if there is a way to submit an alternative .NET core version to nuget?

**Comment by riezebosch** [comment]
See my PR: https://github.com/Real-Serious-Games/C-Sharp-Promise/pull/26

**Comment by nguyendangdung** [comment]
Aren't async/await good enough?

**Comment by ashleydavis** [comment]
Sure, but you need compiler support for that. If you don't have compiler support for it then you can't use async/await. 

Besides that async/await is actually built on top of promises (they are called tasks in C#, but it's the same concept).

So if you want to use async/awaits it's actually good to understand how promises work, because that's what's underneath async/await. 

In addition if you want to do parallel processing with async/await you'll need to bust out the promises anyway because async/await doesn't support that! 

So as you can see it's a little more complicated than you thought.

**Comment by RoryDungan** [comment]
As far as I know, async/await is supported on all versions of .NET Core and .NET 4.5+, so if that does what you need then by all means use that. As Ash said, there are still some situations where you may find promises useful though. 

I'm still not sure what the best way to support building DLLs for both .NET Core and .NET 3.5 is, but the source for the library should compile fine if you change the project to target .NET Core.

**Comment by RoryDungan** [comment]
As of v3.0.1, I've set up the project to build for both .NET Framework 3.5 and .NET Standard 2.0, which supports .NET Core 2.0 and up.
