### ISSUE TITLE
Returning an "empty" promise?

### ISSUE THREAD

**Issue by nah0y** [Real-Serious-Games/C-Sharp-Promise#28]
Hey guys!
First of all, thanks a LOT for this super awesome library. Code is so much cleaner thanks to it!

Question:
I have something like that:

```
Picture.Exists()
.Then(exists =>
{
    if (exists)
    {
        return Picture.Download();
    }
    else
    {
        // What should I do here to finish the promise and not go to the next "Then"?
    }
})
.Then(byteArray =>
{
    // Do something with the byte array
});
```

My question is in the comment of the code.
If the file does not exists, I don't want to go to the next Then. And the compiler is asking me to return something but... what should I return?

Thanks a lot!

**Comment by ashleydavis** [comment]
In this case you should throw an exception. Consider creating an PictureNotException. 

Throwing an exception is the only way to terminate a chain of promises.

**Comment by nah0y** [comment]
Perfect thanks!
How about returning a new Promise<byte[]> for example (and call .Resolve on it before returning it)?

**Comment by zsoi** [comment]
If "No picture" is a valid result that can be handled in your resolution chain, you could just return `null` as well (that'd be similar to JS behavior, where functions with no explicit return will return `undefined`).

Otherwise, I'd go with Ashleys approach and throw an exception and then handle the rejection accordingly, as that will have the result you want it to have (skip the resolution handlers until the next rejection handler). Also, for me, the code looks much cleaner as the "if-error-then" case is handled implicitely by the resolution chain and you don't need synchronous flow control to handle errors:

`data = Fetch()
if(data) {
  return data;
} else {
  return replacementData;
}`

would convert to (assuming fetch() would reject the returned promise correctly)

`return Fetch().Then(x => x).Catch(e => replacement);`

**Comment by nah0y** [comment]
Thanks @zsoi ;)

**Comment by ashleydavis** [comment]
I should add it's perfectly ok to use some kind of 'empty' value. @zsoi has said `null`, but an empty byte array would also work:

```
Picture.Exists()
.Then(exists =>
{
    if (exists)
    {
        return Picture.Download();
    }
    else
    {
        // What should I do here to finish the promise and not go to the next "Then"?
       return new byte[0];
    }
})
.Then(byteArray =>
{
    // Do something with the byte array
});
```
