### ISSUE TITLE
Running Promises of different Types in Parallel

### ISSUE THREAD

**Issue by dp0ch** [Real-Serious-Games/C-Sharp-Promise#33]
Is there any way to run Promises of different Types in parallel in the current version that I'm missing?
As it stands it seems like I'm only able to use `Promise<T>.All`with Promises of Type T.

I think it would be useful if there was an overload for `Promise.All` that took Promises of different types as arguments and returns a `Promise<Tuple<T1, T2>>` or something. 

e.g.

```c#
var p1 = Promise<string>.Resolved("str");
var p2 = Promise<int>.Resolved(42);

Promise.All(p1, p2)
  .Done((Tuple<string, int> vals)=>{
    ...
  });
```

**Comment by RoryDungan** [comment]
Unfortunately running Promise.All with promises of different types is not supported. We currently don't have any plans to implement this as it would be very difficult to implement something like you've suggested without breaking the type-safety of the promises. 

Also, Promise.All returns a Promise of an IEnumerable of the type of the input promises, so you can't cast it to a Tuple like in the code shown. Aside from the fact that for most use cases an IEnumerable is what you want from the result of Promise.All rather than a Tuple, we cannot add built-in support for Tuples as we need to support .NET 3.5 and Tuples were only introduced in .NET 4.0. 

For your use case I would probably recommend just writing a function that takes the types you're expecting, runs all the promises and returns a Tuple<string, int>. Have a look at the source of Promise.All for an example of how this can work.

**Comment by dp0ch** [comment]
Why would it break type-safety?
I have an example Implementation here of the aforementioned overload here -> https://gist.github.com/dp0ch/3ac8fd8855a4a2fa38143aac42c9d386. 
Could you maybe brush over it and tell me why this approach isn't a good idea?

I know that `Promise.All` returns a Promise of an `IEnumerable`. I wasn't trying to cast it to a Tuple I was showcasing how the proposed overload would look like in Usage. As for Tuples not being supported in .NET 3.5 - I forgot about that because I always import my Util Library into any new Unity Project which includes a Tuple Implementation but I don't even think it would be too crazy to just include such a data type for the purpose of this All overload. Only being able to run Promises of the same type seems like a really restricting Limitation to me.

**Comment by ashleydavis** [comment]
It would break type safety because a generic IEnumerable can't host different types, it can only contain a single type. To achieve this with IEnumerable you'd have to use the non-generic version and as such you would be dropping type safety.

I had a look at your gist and I really like your Tuple version Promise.All. @RoryDungan you should consider including this in the library. Of course you'd have to include the Tuple class and make sure it doesn't conflict with the Tuple class in .NET 4.5 (otherwise our 4.5 users won't be impressed).

**Comment by RoryDungan** [comment]
That's a good idea. @dp0ch I took your gist and incorporated it into the library.

**Comment by KirikoroStudios** [comment]
How do I use this functionality?

I have version 1.2.2 and I cannot use Promise.All on promises with different return types...

**Comment by RoryDungan** [comment]
Use `PromiseHelpers.All`, not `Promise.All`. This returns a tuple of values once all the promises have resolved, although since .NET 3.5 doesn't have built-in tuples it uses our own `RSG.Tuple` class, which should have all the same functionality anyway.

There are some examples of this in the unit tests - see `PromiseTests.combined_promise_of_multiple_types_is_resolved_when_children_are_resolved()`
