### ISSUE TITLE
Interrupting a promise sequence from the outside? 

### ISSUE THREAD

**Issue by TiborUdvari** [Real-Serious-Games/C-Sharp-Promise#36]
I'm trying to interrupt a promise sequence from the outside of the sequence.

I am launching some animations and behaviours that I would like to simply kill if a user decides to go back to the menu. How would I be able to achieve this? 

    Promise startPromise;

	void Start() {
		Invoke ("Test", 0.1f);
		startPromise = Promise.Sequence(
			() => speechBubble.Say(truttaSpeech),
			() => Promise.All(
				ShowMenu(true),
				Promise.Sequence(
					() => phoneContainerUI.Grow (),
					() => phoneUI.Ring(MDRPhoneUI.VIDEO_PATH_STAGE2, 2, false, true)
				)
			)
		).Catch(exception => {
			Debug.Log("PROMISE INTERRUPT WAS CALLED");
		}).Then(() => {
			Debug.Log("PROMISE HAS COMPLETED SUCCESFULLY");
		}) as Promise;

	}

	void Test() {
		startPromise.Reject (new Exception("Invoke rejection test"));
	}

**Comment by RoryDungan** [comment]
That code you wrote should work, although actions that can be cancelled aren't really what promises are designed for so you may find it difficult to use them for those kind of situations. A more typical use case for promises might be sending a request to a remote server via HTTP or a database, where the operation will take an indeterminate amount of time so you don't want the application to hang, but you are unlikely to want to cancel it while it's in progress.

For your use case you may find that a promise is the best fit, but it is also worth looking into other solutions like [state machines](https://github.com/Real-Serious-Games/Fluent-State-Machine) or [behaviour trees](https://github.com/codecapers/Fluent-Behaviour-Tree). 

That said, there is an alternative method you can use for cancelling a promise if you'd rather not use exceptions, and that is _Promise.Race_. Using Promise.Race you can specify a second promise to run in parallel with your other sequence and once that promise is resolved, the other promise will be cancelled:
```
// Resolve this promise when you want to cancel the other one.
var backToMenu = new Promise();

startPromise = Promise.Race(
        backToMenu,
        Promise.Sequence(
            () => speechBubble.Say(truttaSpeech),
            () => Promise.All(
                ShowMenu(true),
                Promise.Sequence(
                    () => phoneContainerUI.Grow (),
                    () => phoneUI.Ring(MDRPhoneUI.VIDEO_PATH_STAGE2, 2, false, true)
                )
            )
        )
    ).Then(() => {
        Debug.Log("PROMISE HAS COMPLETED SUCCESFULLY");
    }) as Promise;

// This would be called when we want to stop the other promise
backToMenu.Resolve();
```

Also, any promise created through the PromiseTimer can be cancelled although from your code it didn't look like you were using PromiseTimer so that would probably not be a help to you.

**Comment by ashleydavis** [comment]
Promise.Race doesn't cancel anything. All of it's promises will run to completion.

Promise.Race simply resolves or rejects when the first promises resolves or rejects. But the other promises continue to run until they complete.

There is no standard way to cancel a promise. If you control the code you can throw an exception and that will reject the promise. But it's not very elegant.

**Comment by RoryDungan** [comment]
Ah okay, my mistake. Updated my previous comment
