### ISSUE TITLE
Using waitfor and promiseTimer update

### ISSUE THREAD

**Issue by sweetclimusic** [Real-Serious-Games/C-Sharp-Promise#40]
Hi I've seen the article on what can go wrong.  I'm wanting to replace my StartCorutine that has a yeild waitforseconds in a lateupdate. with Waitfor. 

I'm having difficulties understanding how to implement this properly with the example of timed promises in the article. 

First is this a mistake? should it be called WaitFor, why is this local function it named after the built in function name? 
    
    PromiseTimer promiseTimer = new PromiseTimer();

    IPromise WaitFor(float timeToWait)
    {
        return promiseTimer.WaitFor(timeToWait);
    }

So I have a `_promiseTimer.Update(Time.timeDelta)` in LateUpdate, I understand that this updates the timer inside PromiseTimer but is it needed? What I am confused with, where to call my waitFor.  I don't have anything to watch except time passed. I want to achieve with my promise, after x secs go do the function in the waitfor.  Do i just put `promise.WairFor(seconds)` in LateUpdate.
I know I can assign a promise as a return to the corutine, should I use that approach instead of removing my existing corutine?

thanks

**Comment by adamsingle** [comment]
Hi Sweetclimusic

The PromiseTimer is a manager of sorts. It can spin up a promise and hand it to you, matching it to a predicate. It handles watching the predicates for truthful evaluations and calling `Resolve()` on the associated promise once that condition is met. This is why `PromiseTimer.Update(deltaTime)` needs to be called in a monobehaviour `Update()` method. It uses that tick to evaluate the predicate, which can be time related. 

In the case of the `WaitFor()` you're working with a helper function that is running a predicate that tests for `elapsedTime` since the promise was started being higher than the provided seconds. Once that happens, the PromiseTimer will call Resolve on the associated promise. 

So, to use this, you don't want any promise functionality in a method that is called every tick. The only thing you need in there is the `PromiseTimer.Update()` method. What you want to do is simply call 

```
_promiseTimer.WaitFor(timeToWait)
    .Then(() => DoSomething());
```

This will call the `DoSomething()` method after `timeToWait` seconds has passed. The idea is to replace you coroutines with promises to get much cleaner code that can easily be sequenced together.

here's a more complete, though superfluous, example:

```
private promiseTimer = new PromiseTimer();
void Update()
{
    promiseTimer.Update(Time.deltaTime);
}

public void TriggerDelayedDebug(float seconds)
{
    promiseTimer.WaitFor(seconds)
        .Then(() => WriteDebugLine());
}

private void WriteDebugLine()
{
    Debug.Log("This is debug output");
}
```

I hope this clears it up for you

**Comment by sweetclimusic** [comment]
Hi and thanks, it does clarify a lot. I've not been able to test, but a follow up would be. does the waitfor loop? after every 'timetowait' seconds pass, execute or does it run only once based on time in promisetimer.update  passed since it started? So if i want my promise to run every 5 seconds is waitfor(5).then(() => dostuff()) enough or as i'm currently thinking, dostuff returns waitfor(5).then(() => dostuff()) ?

**Comment by ashleydavis** [comment]
A promise can only be resolved or rejected once. So no it doesn't loop.

You should consider using behaviour trees. I have written about this in the past (http://www.what-could-possibly-go-wrong.com/fluent-behavior-trees-for-ai-and-game-logic/).

If you are after a visual behaviour tree editor I can recommend Behaviour Designer on the Asset Store (https://www.assetstore.unity3d.com/en/#!/content/15277).

**Comment by adamsingle** [comment]
What you're saying could also be described as a stream of events, it may be worth looking into Reactive Extensions. There is an amazing unity Asset called UniRX that I would recommend checking out [https://www.assetstore.unity3d.com/en/#!/content/17276](https://www.assetstore.unity3d.com/en/#!/content/17276)
What we're saying is it could be done with promises, but not cleanly and there are definitely better tools in the programmer's toolbox.

**Comment by sweetclimusic** [comment]
Hi and thanks,  
I've heard and read about UniRx and Behavior Design, and I'm not about that reactive programming yet or designing AI. One tool at a time for me,  I will implement this particular wait timer with a coroutine that uses promises as the unity knights blog demonstrated which is how I learnt about this Library. Thanks for all the help.
