### ISSUE TITLE
ArgumentException on Catch method and (ab)use of Refletions

### ISSUE THREAD

**Issue by cgarciae** [Real-Serious-Games/C-Sharp-Promise#5]
I am getting an `ArgumentException` on `Catch` at runtime when the promise is Resolved (I think)

> ArgumentException: The field handle and the type handle are incompatible.
System.Reflection.FieldInfo.GetFieldFromHandle (RuntimeFieldHandle handle, RuntimeTypeHandle declaringType) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/FieldInfo.cs:171)
RSG.Promise`1[UnityEngine.GameObject].Catch (System.Action`1 onRejected) (at Assets/Lib/CSharpPromises/Promise.cs:431

The error occures on this line in the code
```c#
Argument.NotNull(() => onRejected);
```
and looking at the internals it uses scary machinery like
```c#
var value = parameter.Compile().Invoke();
```
which makes me wonder if this would run on iOS. Commenting the `Argument.NotNull` makes the code work fine. Why the use of reflection for a Promise library?

**Comment by ashleydavis** [comment]
It doesn't use reflection. The scary code you are looking at is C# expression trees which are very useful in certain situations.

The code that is causing the issue is simply for debug argument checking and is not fundamental to the promises library. If it causes a problem on iOS we will most likely remove it from the production code

Can you please provide example code that causes the exception?

We are testing on iOS this week, so your example code will really come in handy for that.

**Comment by cgarciae** [comment]
I'll provide an example tomorrow ;)
Thanks for the info!

**Comment by Renanse** [comment]
fwiw, I have made a lot of progress getting your promise library working on iOS, but had to remove the calls to Argument.NotNull to do so (in fact, the only dependencies on the RSG Utils library now are 3 methods in your Linq extensions.)  I'll try to get together a pull request later today if my kids will spare me some free time (it's a holiday in the US.)

**Comment by ashleydavis** [comment]
Great, I'll look at your PR as soon as it comes in.
