### ISSUE TITLE
EnumerableExt.LazyEach<T> is unused.

### ISSUE THREAD

**Issue by sindrijo** [Real-Serious-Games/C-Sharp-Promise#53]
As of the current version this method is unused by the code in this library, should it be removed?

**Comment by RoryDungan** [comment]
I think it may have been used at one point but yeah I guess it's probably not needed any more. 

Since it is declared as public I would be reluctant to remove it completely until a major version bump, just in case someone else's code relies on it. On the other hand, you could argue that because it's not part of the documented API the rule that changes should only be made in a major release doesn't apply (see [semver](https://semver.org/) rule no. 8).

tbh I'm also not sure why EnumerableExt.Empty exists either because the same functionality is already in the regular .NET Enumerable class. 

We could probably make all these methods internal or remove them pretty easily anyway since they're not really part of the scope of a promise library, although they're not really doing any harm either. @ashleydavis @Edycer what do you think?

**Comment by RoryDungan** [comment]
I deleted this anyway for the v2 release
