### ISSUE TITLE
Error when building for Hololens

### ISSUE THREAD

**Issue by ronneke1996** [Real-Serious-Games/C-Sharp-Promise#73]
After building my Unity project for the Hololens this packages breaks. 

In the Unity editor it works fine. I included the dll in my assets/packages folder. 
I'm using Unity 2017.3.1p1. I also tried installing the package via Nuget, but I still get an error.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IPromise<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'RSG.Promise, Version=3.0.0.0, Culture=neutral, PublicKeyToken=7019fe0722eef3a4'.
```

**Comment by RoryDungan** [comment]
I think Hololens uses Universal Windows Platform instead of Mono/.NET 3.5. Since the DLL is set up to compile for .NET 3.5, you may need to recompile it for UWP. Alternatively, you can just try copying the .cs files from the root of your repository directly into your Assets folder instead of using the DLL.

**Comment by RoryDungan** [comment]
In future it would be good to distribute packages built for UWP and .NET Core via Nuget in addition to .NET 3.5. There was a pull request for that functionality at one point (#26), but it never got finished.

**Comment by RoryDungan** [comment]
Closing because the current version of the Nuget package now includes a build for .NET Standard 2.0, which [supports UWP](https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/).
