### ISSUE TITLE
Support .NET Standard and 3.5 into the same Unity project

### ISSUE THREAD

**Issue by jdnichollsc** [Real-Serious-Games/C-Sharp-Promise#90]
Hi guys,
Some Unity users have reported the same issue with the RSG.Promise library:
- https://github.com/proyecto26/RestClient/issues/30
- https://github.com/proyecto26/RestClient/issues/35
- https://github.com/proyecto26/RestClient/issues/38

So, my question is... Is there an easy way to support the two frameworks? (Depending on the selected platform, the respective DLL is loaded to avoid duplicate reference errors) 
Honestly, I don't know, I don't have a lot of experience with Unity.

This is the plugin from the Unity Store https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501

Any recommendation is very appreciated 👍

**Comment by RoryDungan** [comment]
The easiest way to fix this would probably be to just include the source for C# Promise instead of the compiled DLL. If you have to only ship one version of the DLL I'd probably suggest still using the .NET 3.5 version because that will work with older .NET 3.5 projects as well as ones targeting the full .NET 4.x framework. It just won't support .NET Standard or UWP projects.

I had a quick look online and in Unity and it doesn't look like there's a way built-in to enable or disable DLLs depending on the .NET runtime.
