### ISSUE TITLE
Create an Unity Package of this library

### ISSUE THREAD

**Issue by jdnichollsc** [Real-Serious-Games/C-Sharp-Promise#98]
Hi guys,
I was wondering if you can include a **.unitypackage** file from the [releases](https://github.com/Real-Serious-Games/C-Sharp-Promise/releases) of this project with the source code and the README.

Let me know and thanks in advance,
Juan

**Comment by RoryDungan** [comment]
I've created a [package](https://openupm.com/packages/com.rsg.promise/) of this library on OpenUPM so it can be added easily via the package manager. This is preferable to **.unitypackage** files because the Unity Package Manager can keep track of versions, package files are stored separately to your Assets folder so don't get mixed up with your own assets, you can remove the package without having to worry about missing any files, and when upgrading the package, files that are no longer needed are deleted automatically.

**Comment by jdnichollsc** [comment]
Ohh very interesting, thanks!! 👍

**Comment by jdnichollsc** [comment]
If I want to upload the RestClient too, what's the **package.json** to create the package?

<img width="452" alt="Captura de Pantalla 2020-04-02 a la(s) 12 10 34 a  m" src="https://user-images.githubusercontent.com/2154886/78212814-779d9380-7476-11ea-9f12-d366a0690fac.png">

Thanks in advance!

**Comment by RoryDungan** [comment]
You'll need to create one - [see the Unity docs for details](https://docs.unity3d.com/Manual/upm-manifestPkg.html).

I'd also recommend creating your package out as an [embedded package](https://docs.unity3d.com/Manual/CustomPackages.html#EmbedMe) and then once you have a Git repo with just the package in it trying out [installing it via the Git URL](https://docs.unity3d.com/Manual/upm-ui-giturl.html) to make sure that it works before adding to OpenUPM.
